// / Flutter icons GeoFreshIcons
// / Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
// / This font was generated by FlutterIcon.com, which is derived from Fontello.
// /
// / To use this font, place it in your fonts/ directory and include the
// / following in your pubspec.yaml
// /

// /
// /
// /
import 'package:flutter/widgets.dart';

class GeoFreshIcons {
  GeoFreshIcons._();

  static const _kFontFam = 'GeoFreshIcons';
  static const String _kFontPkg = null;

  static const IconData geo_fresh_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
